### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Tereseus** [JohnnyKrup/JammingProject#1]
> ## Rubric Score
> ### Criteria 1: CRA Project Creation & Structure
> * **Score Level**: 4/4 (Exceeds Expectations)
> * _Comment(s)_:  Your file structure is good.  You made a CRA app and all of the components are properly located inside of folders, with the file paths working as well.  Nice work!
> 
> ### Criteria 2: Data Flow
> * **Score Level**: 2/4 (Needs some work)
> * _Comment(s)_: Unfortunately, your search leads to this error:

![image](https://user-images.githubusercontent.com/19315896/56865135-7deadc00-6998-11e9-8687-100939a181e1.png)

and then this error:

![image](https://user-images.githubusercontent.com/19315896/56865245-c6ef6000-6999-11e9-91f3-c8087916959a.png)

> It does not redirect you the redirect page for Spotify. What did you set up in the Spotify developer portal? Going directly to:

>https://jamming-backend.herokuapp.com/login

>As you have in your code does seem to work. Local host transfer to the login does not, however.

> 
> ### Criteria 3: Syntax
> * **Score Level**: 3/4 (Meets Expectations)
> * _Comment(s)_: You hit upon all of the syntax requirements here.  You used className when applying classes and used JSX instead of pure HTML.  Make sure to add keys to each of the tracks in your track list. 
> 
> ### Criteria 4: DRY Code/Style
> * **Score Level**: 3/4 (Meets Expectations)
> * _Comment(s)_: You did well keeping your code "DRY."  You should look into separating out the beginning of the API urls into a variable as this allows you to change the base url of the API for all endpoints that used it by writing once, instead of updating each method separately. Also a great job on your comments/notes in your code, it made it very easy to review.  Good job.
> 
> ### Overall Score: 12/16
> Overall, you did an ok job with this project. You implemented all of the features of the project and wrote "DRY" code but while it works hosted on heroku it does not redirect correctly through local host. Once you fix the data flow through the app and finish working with the Spotify API your project will be complete.

**Comment by JohnnyKrup** [comment]
Hi Tzuridis

Thanks a lot for your review.
That is really strange that you are experiencing issues with the data flow, while running the local version.
In the devTool of Spotify I added, localhost:8888/callback as well as heroku.../callback

When I run the code locally the following happens:
**Scenario Local:**
- Open a Git Bash window and go to the **server** folder inside the jamming-project
- execute the export SPOTIFY_CLIENT_ID=XXXX and the export SPOTIFY_CLIENT_SECRET=YYYY according your Spotify account
- run **npm start** to start the server
- open another console window and navigate to the JammingProject folder to run **npm start** to run also the client
- when clicking on search without entering a term, nothing should happen
- when you click search with a term it checks if you are logged in to Spotify
- in case you are not logged in, you are asked to identify and give the jamming app the needed rights
- the localhost:3000 site is reloaded and the search term needs to be entered again
- now a list with max. 5 results are displayed, since I limited the results to 5

I can see the **unhandled rejection (type error)** for a couple of seconds when I enter the https://jamming-codecademy.herokuapp.com as a starting point, before it redirects to the heroku backend to go through the Spotify identification process.

**Comment by Tereseus** [comment]
Ok it must be what you setup as the endpoint in the developer portal for Spotify since it works for Heroku. The redirect should be instant though not with a few seconds delay. To prevent the error from appearing you can rewrite the flow synchronously but as for the functionality, everything works on Heroku.

**Comment by JohnnyKrup** [comment]
What I changed:
- stored beginning of URLs in a variable
- removed the heroku functionality, projects works on localhost only
- added the track ID as a key to all tracks

**Comment by JohnnyKrup** [comment]
I will upload the project again, so that you can check if the above mentioned corrections work as expected

**Comment by JohnnyKrup** [comment]
It is updated and ready for review

**Comment by Tereseus** [comment]
You uploaded the project through codecademy's portal? If so the project will likely be assigned to another advisor to be graded.

**Comment by JohnnyKrup** [comment]
I updated the github project, where you left a comment, not through the
codecademy portal.

**Comment by JohnnyKrup** [comment]
@Tzuridis
Hi there will you review the changes, or should I upload the project again, via the codebase upload mechanism?
Sorry for the wuestion but I didn’t get your last message and how to proceed.
have a great day
Graziano

**Comment by Tereseus** [comment]
Hi Graziano sorry I didn't see your last message. You have to re-upload it
through the codebase mechanism as I am unable to mark it as complete.

**Comment by JohnnyKrup** [comment]
ok will do, thank you fir the reply.
